// Platform-admin console navigation. Detail routes (e.g. /admin/users/:id)
// are intentionally absent here — they are reached from their list pages.
import type { ConsoleNavSection } from "@/components/shared/ConsoleLayout"
import {
  BoxesIcon,
  BuildingIcon,
  CoinsIcon,
  ContainerIcon,
  CpuIcon,
  CreditCardIcon,
  DatabaseBackupIcon,
  DatabaseIcon,
  FileClockIcon,
  GaugeIcon,
  GiftIcon,
  GlobeIcon,
  HardDriveIcon,
  HeartPulseIcon,
  InboxIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LifeBuoyIcon,
  NetworkIcon,
  PackageIcon,
  PieChartIcon,
  ReceiptTextIcon,
  ScrollTextIcon,
  ServerIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  TagIcon,
  UsersIcon,
  WalletIcon,
  WorkflowIcon,
} from "lucide-react"

export const adminNav: ConsoleNavSection[] = [
  {
    title: "Platform",
    items: [
      { title: "Dashboard", url: "/admin", icon: LayoutDashboardIcon },
      { title: "Users", url: "/admin/users", icon: UsersIcon },
      { title: "Organizations", url: "/admin/organizations", icon: BuildingIcon },
      { title: "Orphan resources", url: "/admin/orphans", icon: BoxesIcon },
      { title: "Tickets", url: "/admin/tickets", icon: LifeBuoyIcon },
      { title: "Audit logs", url: "/admin/audit-logs", icon: ScrollTextIcon },
      { title: "Landing content", url: "/admin/landing", icon: ScrollTextIcon },
      { title: "Documentation", url: "/admin/docs", icon: ScrollTextIcon },
      { title: "Blog", url: "/admin/blog", icon: ScrollTextIcon },
    ],
  },
  {
    title: "Security",
    items: [
      { title: "Security hub", url: "/admin/security", icon: ShieldCheckIcon },
      { title: "Incidents", url: "/admin/security/incidents", icon: ShieldCheckIcon },
      { title: "Blocked networks", url: "/admin/security/blocked-networks", icon: GlobeIcon },
      { title: "Feature flags", url: "/admin/security/feature-flags", icon: FileClockIcon },
      { title: "App settings", url: "/admin/security/app-settings", icon: FileClockIcon },
    ],
  },
  {
    title: "Proxmox",
    items: [
      { title: "Providers", url: "/admin/providers?kind=proxmox", icon: ServerIcon },
      { title: "Nodes", url: "/admin/providers?kind=proxmox&section=nodes", icon: CpuIcon },
      { title: "Storages", url: "/admin/providers?kind=proxmox&section=storages", icon: HardDriveIcon },
      { title: "Containers", url: "/admin/providers?kind=proxmox&section=containers", icon: ContainerIcon },
      { title: "Backup jobs", url: "/admin/providers?kind=proxmox&section=backup-jobs", icon: DatabaseBackupIcon },
      { title: "HA", url: "/admin/providers?kind=proxmox&section=ha", icon: HeartPulseIcon },
      { title: "Firewall", url: "/admin/providers?kind=proxmox&section=firewall", icon: ShieldCheckIcon },
      { title: "SDN", url: "/admin/providers?kind=proxmox&section=sdn", icon: NetworkIcon },
      { title: "Ceph", url: "/admin/providers?kind=proxmox&section=ceph", icon: LayersIcon },
      { title: "Pools", url: "/admin/providers?kind=proxmox&section=pools", icon: BoxesIcon },
      { title: "Clone (VM+LXC)", url: "/admin/providers?kind=proxmox&section=clone", icon: BoxesIcon },
      { title: "Templates", url: "/admin/providers?kind=proxmox&section=templates", icon: LayersIcon },
      { title: "Snapshots", url: "/admin/providers?kind=proxmox&section=snapshots", icon: DatabaseBackupIcon },
      { title: "Diagnostics", url: "/admin/providers?kind=proxmox&section=diagnostics", icon: GaugeIcon },
      { title: "Performance", url: "/admin/providers?kind=proxmox&section=perf", icon: GaugeIcon },
    ],
  },
  {
    title: "Onidel",
    items: [
      { title: "Providers", url: "/admin/providers?kind=onidel", icon: ServerIcon },
      { title: "Catalog", url: "/admin/providers?kind=onidel&section=catalog", icon: LayersIcon },
      { title: "Health", url: "/admin/providers?kind=onidel&section=health", icon: HeartPulseIcon },
      { title: "Health detail", url: "/admin/providers?kind=onidel&section=health-detail", icon: HeartPulseIcon },
      { title: "Instances (realtime)", url: "/admin/providers?kind=onidel&section=instances", icon: ContainerIcon },
      { title: "Orders history", url: "/admin/providers?kind=onidel&section=orders", icon: ContainerIcon },
      { title: "Invoices", url: "/admin/providers?kind=onidel&section=invoices", icon: ReceiptTextIcon },
      { title: "Billing sync", url: "/admin/providers?kind=onidel&section=billing-sync", icon: CreditCardIcon },
    ],
  },
  {
    title: "VMware",
    items: [
      { title: "Providers", url: "/admin/providers?kind=vmware", icon: ServerIcon },
      { title: "Hosts", url: "/admin/providers?kind=vmware&section=hosts", icon: CpuIcon },
      { title: "Datastores", url: "/admin/providers?kind=vmware&section=datastores", icon: HardDriveIcon },
      { title: "Inventory", url: "/admin/providers?kind=vmware&section=inventory", icon: HardDriveIcon },
      { title: "Snapshots", url: "/admin/providers?kind=vmware&section=snapshots", icon: DatabaseBackupIcon },
      { title: "Snapshot revert", url: "/admin/providers?kind=vmware&section=snapshots-revert", icon: DatabaseBackupIcon },
      { title: "Migrate (vMotion)", url: "/admin/providers?kind=vmware&section=migrate", icon: ContainerIcon },
      { title: "Performance", url: "/admin/providers?kind=vmware&section=perf", icon: GaugeIcon },
    ],
  },
  {
    title: "Dokploy",
    items: [
      { title: "Dokploy hub", url: "/admin/dokploy", icon: DatabaseIcon },
      { title: "Logs (realtime)", url: "/admin/dokploy/logs", icon: ScrollTextIcon },
      { title: "Projects", url: "/admin/dokploy/app/projects", icon: BoxesIcon },
      { title: "Overview", url: "/admin/dokploy/app/overview", icon: GlobeIcon },
      { title: "Docker", url: "/admin/dokploy/app/docker", icon: HardDriveIcon },
      { title: "Monitoring", url: "/admin/dokploy/app/monitoring", icon: FileClockIcon },
      { title: "Requests", url: "/admin/dokploy/app/requests", icon: InboxIcon },
      { title: "Schedules", url: "/admin/dokploy/app/schedules", icon: WorkflowIcon },
      { title: "Traefik files", url: "/admin/dokploy/app/traefik", icon: ServerIcon },
      { title: "Settings (Dokploy)", url: "/admin/dokploy/app/settings/profile", icon: ShieldCheckIcon },
    ],
  },
  {
    title: "Billing",
    items: [
      { title: "Summary", url: "/admin/billing/summary", icon: PieChartIcon },
      { title: "Reports", url: "/admin/billing/reports", icon: PieChartIcon },
      { title: "Orders", url: "/admin/billing/orders", icon: ShoppingBagIcon },
      { title: "Invoices", url: "/admin/billing/invoices", icon: ReceiptTextIcon },
      { title: "Payments", url: "/admin/billing/payments", icon: CreditCardIcon },
      { title: "Wallets", url: "/admin/billing/wallets", icon: WalletIcon },
      { title: "Coupons", url: "/admin/billing/coupons", icon: TagIcon },
      { title: "Products & plans", url: "/admin/billing/products-plans", icon: PackageIcon },
      { title: "Custom rates", url: "/admin/billing/custom-rates", icon: CoinsIcon },
    ],
  },
  {
    title: "Affiliate program",
    items: [
      { title: "Configuration", url: "/admin/billing/affiliate-config", icon: GiftIcon },
      { title: "Settings", url: "/admin/affiliate/settings", icon: GiftIcon },
      { title: "Earnings", url: "/admin/affiliate/earnings", icon: GiftIcon },
    ],
  },
]
